server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://shuttle.proxy.rlwy.net:33156/railway
    username: root
    password: fDEwqueDFNrZnAFiUSkEbQvIZomWTSVv
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true