server:
  port: ${PORT:8080} # 👈 Railway inyecta la variable PORT

spring:
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3307/railway
    username: root
    password: fDEwqueDFNrZnAFiUSkEbQvIZomWTSVv
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true